### ISSUE TITLE
Won't parse encoded URLs

### ISSUE THREAD

**Issue by Cteljr** [TimothyGu/urltester#4]
It complained bitterly (at least when using Chrome) about this URL:
http://%67%6f%6f%67%6c%65%2e%63%6f%6d

**Comment by TimothyGu** [comment]
Not sure if anything changed, but I think it's fine now. Go doesn't like it but everyone else seems okay with it

![Screenshot from 2023-02-12 23-55-55](https://user-images.githubusercontent.com/1538624/218401550-ec79036e-b646-4c3c-b830-bd39e580dd7f.png)
